dependencies:
  - name: builder
    version: 2.13.9
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: slugbuilder
    version: 2.8.1
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: dockerbuilder
    version: 2.8.4
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: controller
    version: 2.22.1
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: slugrunner
    version: 2.7.1
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: database
    version: 2.7.7
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: fluentd
    version: 2.15.2
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: redis
    version: 2.4.4
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: logger
    version: 2.5.2
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: minio
    version: 2.4.6
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: monitor
    version: 2.11.5
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: nsqd
    version: 2.5.3
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: registry
    version: 2.6.2
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: registry-proxy
    version: 1.5.2
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: registry-token-refresher
    version: 1.2.3
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: router
    version: 2.19.2
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
  - name: workflow-manager
    version: 2.6.3
    repository: oci://ghcr.io/kingdonb/hephy-workflow-beta
